# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
  - linux
language: R
cache: packages
bioc_packages: RBGL
dist: focal
warnings_are_errors: true

before_install:
  - sudo apt-get -y build-essential libglpk40
